"""
Regression tests for the CBSTM03A statement generation migration.

These tests verify that the Python migration of the COBOL CREASTMT batch
program (CBSTM03A.CBL + CBSTM03B.CBL) produces byte-identical output to
the committed reference files.

Test fixtures
-------------
Input data (CSV, under ``fixtures/``):
    trnx.csv   -- 3 transactions across 2 cards
    xref.csv   -- 2 card cross-reference records
    cust.csv   -- 2 customer records
    acct.csv   -- 2 account records

Reference output (under ``reference/``):
    expected_statement.txt   -- plain-text statement (80-byte records)
    expected_statement.html  -- HTML statement (100-byte records)

The reference files were generated by running::

    python cbstm03a_statement.py \\
        fixtures/trnx.csv fixtures/xref.csv \\
        fixtures/cust.csv fixtures/acct.csv \\
        reference/expected_statement.txt reference/expected_statement.html

after the initial trusted validation against the COBOL output specification.
To regenerate after a legitimate output change, re-run the command above and
commit the updated reference files.

Test data design
-----------------
* Card 4111111111111111 (customer John Michael Smith, account 80000000001):
  two transactions -- one positive ($45.67) and one negative (-$22.50) to
  exercise trailing-minus sign formatting and correct total computation.
* Card 4222222222222222 (customer Jane Ann Doe, account 80000000002):
  one transaction ($128.99) to verify multi-statement output.
"""

from __future__ import annotations

import os
import tempfile
from decimal import Decimal
from pathlib import Path

import pytest

from cbstm03a_statement import (
    StatementGenerator,
    format_pic_9_99_minus,
    format_pic_z_99_minus,
    generate_statements,
)
from cbstm03b_io import FileStore, TrnxRecord, XrefRecord, CustomerRecord, AccountRecord

_HERE = Path(__file__).resolve().parent
_FIXTURES = _HERE / "fixtures"
_REFERENCE = _HERE / "reference"


# ===================================================================
# Unit tests for COBOL numeric edit-picture formatters
# ===================================================================


class TestPic9_99Minus:
    """PIC 9(9).99- -- no zero suppression, trailing sign."""

    def test_positive_value(self):
        assert format_pic_9_99_minus(Decimal("1500.75")) == "000001500.75 "

    def test_negative_value(self):
        assert format_pic_9_99_minus(Decimal("-1500.75")) == "000001500.75-"

    def test_zero(self):
        assert format_pic_9_99_minus(Decimal("0.00")) == "000000000.00 "

    def test_large_value(self):
        assert format_pic_9_99_minus(Decimal("999999999.99")) == "999999999.99 "

    def test_width(self):
        result = format_pic_9_99_minus(Decimal("42.00"))
        assert len(result) == 13


class TestPicZ_99Minus:
    """PIC Z(9).99- -- zero-suppressed integer, trailing sign."""

    def test_positive_value(self):
        assert format_pic_z_99_minus(Decimal("45.67")) == "       45.67 "

    def test_negative_value(self):
        assert format_pic_z_99_minus(Decimal("-22.50")) == "       22.50-"

    def test_zero(self):
        assert format_pic_z_99_minus(Decimal("0.00")) == "         .00 "

    def test_large_value(self):
        assert format_pic_z_99_minus(Decimal("128.99")) == "      128.99 "

    def test_width(self):
        result = format_pic_z_99_minus(Decimal("1.00"))
        assert len(result) == 13


# ===================================================================
# Unit tests for FileStore I/O layer
# ===================================================================


class TestFileStore:
    """Basic I/O layer tests."""

    def test_sequential_read_trnx(self):
        store = FileStore(
            str(_FIXTURES / "trnx.csv"),
            str(_FIXTURES / "xref.csv"),
            str(_FIXTURES / "cust.csv"),
            str(_FIXTURES / "acct.csv"),
        )
        rc = store.open("TRNXFILE")
        assert rc == "00"

        rc, rec = store.read_sequential("TRNXFILE")
        assert rc == "00"
        assert rec.trnx_card_num == "4111111111111111"
        assert rec.trnx_amt == Decimal("45.67")

    def test_keyed_read_customer(self):
        store = FileStore(
            str(_FIXTURES / "trnx.csv"),
            str(_FIXTURES / "xref.csv"),
            str(_FIXTURES / "cust.csv"),
            str(_FIXTURES / "acct.csv"),
        )
        store.open("CUSTFILE")
        rc, rec = store.read_by_key("CUSTFILE", "100000001", 9)
        assert rc == "00"
        assert rec.cust_first_name == "John"

    def test_keyed_read_not_found(self):
        store = FileStore(
            str(_FIXTURES / "trnx.csv"),
            str(_FIXTURES / "xref.csv"),
            str(_FIXTURES / "cust.csv"),
            str(_FIXTURES / "acct.csv"),
        )
        store.open("CUSTFILE")
        rc, rec = store.read_by_key("CUSTFILE", "999999999", 9)
        assert rc == "23"
        assert rec is None

    def test_sequential_read_eof(self):
        store = FileStore(
            str(_FIXTURES / "trnx.csv"),
            str(_FIXTURES / "xref.csv"),
            str(_FIXTURES / "cust.csv"),
            str(_FIXTURES / "acct.csv"),
        )
        store.open("XREFFILE")
        store.read_sequential("XREFFILE")
        store.read_sequential("XREFFILE")
        rc, rec = store.read_sequential("XREFFILE")
        assert rc == "10"
        assert rec is None


# ===================================================================
# Byte-for-byte regression tests
# ===================================================================


class TestStatementRegression:
    """Compare generated output against committed reference files."""

    @pytest.fixture(autouse=True)
    def setup_output_files(self, tmp_path):
        self.stmt_output = str(tmp_path / "statement.txt")
        self.html_output = str(tmp_path / "statement.html")
        generate_statements(
            str(_FIXTURES / "trnx.csv"),
            str(_FIXTURES / "xref.csv"),
            str(_FIXTURES / "cust.csv"),
            str(_FIXTURES / "acct.csv"),
            self.stmt_output,
            self.html_output,
        )

    def test_plain_text_byte_identical(self):
        """Plain-text output must match reference/expected_statement.txt."""
        expected = (_REFERENCE / "expected_statement.txt").read_text()
        actual = Path(self.stmt_output).read_text()
        assert actual == expected, (
            "Plain-text statement output differs from reference. "
            "Run the generator and diff against reference/expected_statement.txt."
        )

    def test_html_byte_identical(self):
        """HTML output must match reference/expected_statement.html."""
        expected = (_REFERENCE / "expected_statement.html").read_text()
        actual = Path(self.html_output).read_text()
        assert actual == expected, (
            "HTML statement output differs from reference. "
            "Run the generator and diff against reference/expected_statement.html."
        )

    def test_plain_text_record_width(self):
        """Every record in the plain-text output must be exactly 80 bytes."""
        with open(self.stmt_output) as f:
            for i, line in enumerate(f, 1):
                content = line.rstrip("\n")
                assert len(content) == 80, (
                    f"Line {i} is {len(content)} chars (expected 80): {content!r}"
                )

    def test_html_record_width(self):
        """Every record in the HTML output must be exactly 100 bytes."""
        with open(self.html_output) as f:
            for i, line in enumerate(f, 1):
                content = line.rstrip("\n")
                assert len(content) == 100, (
                    f"Line {i} is {len(content)} chars (expected 100): {content!r}"
                )

    def test_plain_text_line_count(self):
        """Verify the expected number of output lines."""
        with open(self.stmt_output) as f:
            lines = f.readlines()
        assert len(lines) == 41

    def test_html_line_count(self):
        """Verify the expected number of HTML output lines."""
        with open(self.html_output) as f:
            lines = f.readlines()
        assert len(lines) == 161

    def test_negative_amount_trailing_minus(self):
        """Gas Station transaction (-$22.50) must show trailing minus."""
        with open(self.stmt_output) as f:
            lines = f.readlines()
        gas_line = lines[17].rstrip("\n")
        assert gas_line.endswith("22.50-"), (
            f"Expected trailing minus for negative amount: {gas_line!r}"
        )

    def test_total_accounts_for_negative(self):
        """Total for first statement: 45.67 + (-22.50) = 23.17."""
        with open(self.stmt_output) as f:
            lines = f.readlines()
        total_line = lines[19].rstrip("\n")
        assert "23.17" in total_line, (
            f"Expected total 23.17 for first statement: {total_line!r}"
        )
